import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { generateAll, CHAPTER_INFO, LEVEL_REMAKE_SEED, canonicalLayoutSignature } from '../src/services/generator.js';

const root = new URL('../', import.meta.url);
const target = new URL('src/data/levels.generated.js', root);
const check = process.argv.includes('--check');
if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('usage: node tools/generate-levels.mjs [--check]');
const hash = text => createHash('sha256').update(text).digest('hex');
const baseline = JSON.parse(fs.readFileSync(new URL('art/recipes/retired-level-signatures.json', root), 'utf8'));
if (baseline.schemaVersion !== 1 || baseline.count !== 300 || !Array.isArray(baseline.sha256)
    || baseline.sha256.length !== 300 || baseline.sha256.some(h => typeof h !== 'string' || !/^[0-9a-f]{64}$/.test(h))) {
  throw new Error('invalid retired-level comparison record');
}
const retired = new Set(baseline.sha256);
const started = performance.now();
const { levels, failures } = generateAll(1, 300, { reject: signature => retired.has(hash(signature)) });
if (failures.length || levels.length !== 300) throw new Error(`generation failed: ${JSON.stringify(failures)}`);
const unique = new Set(levels.map(canonicalLayoutSignature));
if (unique.size !== 300) throw new Error('duplicate new layout');
const info = { revision: 'rainpaths-v1', seed: LEVEL_REMAKE_SEED, count: 300,
  retiredComparisonSha256: hash(fs.readFileSync(new URL('art/recipes/retired-level-signatures.json', root))) };
const output = `// Fresh layouts generated by tools/generate-levels.mjs. Edit the generator, then regenerate.\nexport const GENERATION_INFO = ${JSON.stringify(info, null, 2)};\n\nexport const GENERATED_LEVELS = ${JSON.stringify(levels, null, 2)};\n\nexport const GENERATED_CHAPTERS = ${JSON.stringify(CHAPTER_INFO, null, 2)};\n`;
if (check) {
  if (fs.readFileSync(target, 'utf8') !== output) throw new Error('published level data differs from reproducible generation');
} else {
  // All generation and validation complete before replacing the one data file.
  const staged = new URL('src/data/levels.generated.js.tmp', root);
  try { fs.writeFileSync(staged, output); fs.renameSync(staged, target); }
  finally { if (fs.existsSync(staged)) fs.unlinkSync(staged); }
}
const bands = Object.fromEntries(['easy', 'normal', 'hard', 'extreme'].map(band => [band, levels.filter(l => l.diff === band).length]));
console.log(JSON.stringify({ action: check ? 'verified' : 'published', file: fileURLToPath(target), seed: LEVEL_REMAKE_SEED,
  levels: levels.length, uniqueIgnoringRotationReflection: unique.size, retiredMatches: 0, bands,
  elapsedMs: Math.round(performance.now() - started), sha256: hash(output) }, null, 2));
